### ISSUE TITLE
Sensors not showed

### ISSUE THREAD

**Issue by lucajust** [Kalivos/ha_openmediavault#8]
hassio version: 107.7
OMV version: 5.3.9-1

I have followed the instructions to enable this component.  I added the lines on the configuration.yaml and the folder with files in teh "custom-components" folder of mu hassio config.

After reboot of the server, there aren't errors but i can't fine the new sensors on my entities list. 

`- platform: openmediavault
  name: OMV
  host: 'http://192.168.1.57:80'
  username: admin
  password: !secret openmediavault_password
  monitored_conditions:
    -  hostname
    -  version
    -  processor
    -  kernel
    -  system_time
    -  uptime
    -  load_average
    -  cpu_usage
    -  memory_usage`

![image](https://user-images.githubusercontent.com/56367824/78554675-ddd63d80-780b-11ea-8744-2bd7caf320f1.png)

Do you have any suggestions?

**Comment by dkalinai** [comment]
Check developer logs, what do they say?

**Comment by lucajust** [comment]
yes, i saw the log. This is a screenshot:
![image](https://user-images.githubusercontent.com/56367824/78555282-fdba3100-780c-11ea-83dc-312ce255eb24.png)

**Comment by dkalinai** [comment]
There is another issue opened like this: https://github.com/Kalivos/ha_openmediavault/issues/6 

I made a PR but unfortunately developer does not merge it for one reason or the other. I managed to fix it for me.

**Comment by lucajust** [comment]
ok, thanks. I try to modify "setup.py" as yours.

**Comment by lucajust** [comment]
> There is another issue opened like this: #6
> 
> I made a PR but unfortunately developer does not merge it for one reason or the other. I managed to fix it for me.

I modify the parameters and it work correctly. Really thanks

**Comment by dkalinai** [comment]
No worries, there is just a wrong way to call those things in code, not sure how it worked before :)

**Comment by lucajust** [comment]
> No worries, there is just a wrong way to call those things in code, not sure how it worked before :)

isn't the actual developer  insterested to fix it? Could you make a new project to support this component?

**Comment by dkalinai** [comment]
I moved to FreeNas since then :) Frankly have no interest in claiming someone's work. I already did the hard part of finding and rootcausing the problem for the original dev :)

**Comment by lucajust** [comment]
> I moved to FreeNas since then :) Frankly have no interest in claiming someone's work. I already did the hard part of finding and rootcausing the problem for the original dev :)

ok! You did a good job for community. Thanks again!
